const canvas = document.getElementById('draw-canvas'); const ctx = canvas.getContext('2d'); const preview = document.getElementById('preprocessed-canvas'); const previewContext = preview.getContext('2d'); let drawing = false;
ctx.fillStyle = '#18251f'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.lineCap='round'; ctx.lineJoin='round'; ctx.strokeStyle='#f2f7e2'; ctx.lineWidth=28;
function position(event){ const rect=canvas.getBoundingClientRect(); return {x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height}; }
canvas.addEventListener('pointerdown', e => { drawing=true; canvas.setPointerCapture(e.pointerId); const p=position(e); ctx.beginPath(); ctx.moveTo(p.x,p.y); ctx.lineTo(p.x+.1,p.y+.1); ctx.stroke(); });
canvas.addEventListener('pointermove', e => { if(!drawing)return; const p=position(e); ctx.lineTo(p.x,p.y); ctx.stroke(); renderPreview(preprocess()); }); canvas.addEventListener('pointerup',()=>{ drawing=false; recognize(); }); canvas.addEventListener('pointerleave',()=>{ if(drawing){ drawing=false; recognize(); } });
function preprocess(){ const source=ctx.getImageData(0,0,canvas.width,canvas.height).data; let minX=canvas.width,minY=canvas.height,maxX=-1,maxY=-1; for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){if(source[(y*canvas.width+x)*4]>40){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}} if(maxX<0)return Array(784).fill(0); const size=Math.max(maxX-minX+1,maxY-minY+1), temp=document.createElement('canvas'); temp.width=temp.height=28; const t=temp.getContext('2d'); t.fillStyle='#000';t.fillRect(0,0,28,28); const pad=3, scale=22/size; t.drawImage(canvas,minX,minY,maxX-minX+1,maxY-minY+1, pad+(22-(maxX-minX+1)*scale)/2,pad+(22-(maxY-minY+1)*scale)/2,(maxX-minX+1)*scale,(maxY-minY+1)*scale); const raw=t.getImageData(0,0,28,28).data; const pixels=Array.from({length:784},(_,i)=>raw[i*4]/255); let mass=0,sumX=0,sumY=0; pixels.forEach((value,i)=>{mass+=value;sumX+=(i%28)*value;sumY+=Math.floor(i/28)*value}); const shiftX=Math.round(14-sumX/mass),shiftY=Math.round(14-sumY/mass); return pixels.map((_,i)=>{const x=i%28,y=Math.floor(i/28),sourceX=x-shiftX,sourceY=y-shiftY;return sourceX>=0&&sourceX<28&&sourceY>=0&&sourceY<28?pixels[sourceY*28+sourceX]:0}); }
function renderPreview(input){ const image=previewContext.createImageData(28,28); input.forEach((value,index)=>{ const shade=Math.round(value*255); image.data[index*4]=shade; image.data[index*4+1]=shade; image.data[index*4+2]=shade; image.data[index*4+3]=255; }); previewContext.putImageData(image,0,0); }
function renderBars(probabilities){ const bars=document.getElementById('probability-bars'); bars.innerHTML=probabilities.map((value,index)=>`<div class="bar-row ${value===Math.max(...probabilities)?'hot':''}"><span>${index}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(2,value*100)}%"></div></div><span>${Math.round(value*100)}%</span></div>`).join(''); }
async function recognize(){ await DigitModel.ready; const input=preprocess(); renderPreview(input); if(!input.some(value=>value>0))return; const result=DigitModel.forward(input); const best=result.probabilities.indexOf(Math.max(...result.probabilities)); document.getElementById('prediction-digit').textContent=best; document.getElementById('prediction-confidence').textContent=`${Math.round(result.probabilities[best]*100)}% confidence`; document.getElementById('confidence-label').textContent='Signal complete'; renderBars(result.probabilities); NetworkViz.update(result); }
document.getElementById('predict-button').addEventListener('click',recognize); document.getElementById('clear-button').addEventListener('click',()=>{ctx.fillStyle='#18251f';ctx.fillRect(0,0,canvas.width,canvas.height);previewContext.clearRect(0,0,28,28);document.getElementById('prediction-digit').textContent='—';document.getElementById('prediction-confidence').textContent='Draw something to begin';document.getElementById('confidence-label').textContent='Awaiting input';document.getElementById('probability-bars').innerHTML=''; NetworkViz.update({activations:[[...Array(784)].map(()=>0),Array(16).fill(0),Array(16).fill(0),Array(10).fill(.1)],weights:[]});});
document.getElementById('model-status').textContent=DigitModel.status; document.getElementById('predict-button').disabled=true;