const NetworkViz = (() => {
  const canvas = document.getElementById('network-canvas'); const context = canvas.getContext('2d', { willReadFrequently: true });
  const stages = { input: { x: 24, y: 120, size: 180 }, hidden1: { x: 340 }, hidden2: { x: 540 }, output: { x: 760 } };
  let state = { activations: DigitModel.sizes.map((size, index) => Array(size).fill(index === 3 ? .1 : 0)), weights: [] }; let animationTime = 0; let hasSignal = false;
  function neurons(x, count, top = 70, gap = 28) { const compact = count > 20; const start = compact ? 56 : top; const spacing = compact ? 22 : gap; return Array.from({ length: count }, (_, index) => ({ x, y: start + index * spacing })); }
  function drawText(text, x, y, size = 16, align = 'left') { context.fillStyle = '#e9f3ff'; context.font = `700 ${size}px "IBM Plex Mono", monospace`; context.textAlign = align; context.shadowBlur = 8; context.shadowColor = 'rgba(173, 194, 214, 0.8)'; context.fillText(text, x, y); context.shadowBlur = 0; }
  function drawArrow(x1, x2, label) { const color = label === '784 PIXELS' ? '#2f8fff' : '#f04d67'; context.strokeStyle = color; context.lineWidth = 1.5; context.setLineDash([5, 5]); context.beginPath(); context.moveTo(x1, 290); context.lineTo(x2, 290); context.stroke(); context.setLineDash([]); drawText(label, (x1 + x2) / 2, 272, 16, 'center'); context.beginPath(); context.moveTo(x2, 290); context.lineTo(x2 - 9, 283); context.lineTo(x2 - 9, 297); context.closePath(); context.fill(); }
  function roundRect(x, y, width, height, radius) { context.beginPath(); context.moveTo(x + radius, y); context.lineTo(x + width - radius, y); context.quadraticCurveTo(x + width, y, x + width, y + radius); context.lineTo(x + width, y + height - radius); context.quadraticCurveTo(x + width, y + height, x + width - radius, y + height); context.lineTo(x + radius, y + height); context.quadraticCurveTo(x, y + height, x, y + height - radius); context.lineTo(x, y + radius); context.quadraticCurveTo(x, y, x + radius, y); context.closePath(); }
  function drawSignal(x1, x2, offset) { if (!hasSignal) return; const progress = ((animationTime / 1500 + offset) % 1); const x = x1 + (x2 - x1) * progress; const color = offset === 0 ? '#2f8fff' : '#f04d67'; context.shadowBlur = 18; context.shadowColor = color; context.fillStyle = color; context.beginPath(); context.arc(x, 290, 4.5, 0, Math.PI * 2); context.fill(); context.shadowBlur = 0; }
  function draw(time = 0) {
    animationTime = time; context.clearRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#080e10'; context.fillRect(0, 0, canvas.width, canvas.height);
    const input = stages.input; const cell = input.size / 28; context.strokeStyle = '#58696f'; context.lineWidth = 1; context.strokeRect(input.x, input.y, input.size, input.size);
    for (let y = 0; y < 28; y += 1) for (let x = 0; x < 28; x += 1) { const value = state.activations[0][y * 28 + x] || 0; context.fillStyle = `rgb(${Math.round(22 + value * 225)},${Math.round(35 + value * 212)},${Math.round(29 + value * 197)})`; context.fillRect(input.x + x * cell, input.y + y * cell, cell + .3, cell + .3); }
    const first = neurons(stages.hidden1.x, DigitModel.sizes[1], 72, 16); const second = neurons(stages.hidden2.x, DigitModel.sizes[2], 72, 16); const output = neurons(stages.output.x, DigitModel.sizes[3], 112, 38);
    const winningOutput = state.activations[3].indexOf(Math.max(...state.activations[3]));
    const connect = (from, to, layer) => to.forEach((b, bi) => { if (!hasSignal && layer > 0) return; const strongest = from.map((a, ai) => ({ a, ai, weight: state.weights[layer]?.[bi]?.[ai] || 0 })).filter(connection => connection.weight).sort((left, right) => Math.abs(right.weight) - Math.abs(left.weight)).slice(0, 6); strongest.forEach(({ a, ai, weight }) => { const sourceValue = state.activations[layer]?.[ai] || 0; const targetValue = state.activations[layer + 1]?.[bi] || 0; const pulse = .5 + .5 * Math.sin(animationTime / 220 + ai * .7 + bi * .3); const active = Math.min(1, sourceValue * targetValue * 5); const alpha = Math.min(1, .12 + Math.abs(weight) * .45 + active * (.2 + pulse * .22)); const palette = ['#2f8fff', '#f04d67']; const baseColor = layer === 2 && bi === winningOutput ? '#f04d67' : palette[(ai + bi + layer) % palette.length]; const color = `${baseColor}${Math.round(alpha * 255).toString(16).padStart(2, '0')}`; context.strokeStyle = color; context.shadowBlur = 18; context.shadowColor = baseColor; context.lineWidth = Math.min(3, .7 + Math.abs(weight) * .9 + active * pulse * 1.3); context.beginPath(); context.moveTo(a.x, a.y); context.lineTo(b.x, b.y); context.stroke(); context.shadowBlur = 0; }); });
    connect(first, second, 1); connect(second, output, 2); drawArrow(input.x + input.size, stages.hidden1.x - 18, '784 PIXELS'); drawArrow(stages.hidden1.x + 18, stages.hidden2.x - 18, 'RELU'); drawArrow(stages.hidden2.x + 18, stages.output.x - 18, 'SOFTMAX'); drawSignal(input.x + input.size, stages.hidden1.x - 18, 0); drawSignal(stages.hidden1.x + 18, stages.hidden2.x - 18, .33); drawSignal(stages.hidden2.x + 18, stages.output.x - 18, .66);
    if (hasSignal && output[winningOutput]) { const winner = output[winningOutput]; const label = `${winningOutput}: ${Math.round((state.activations[3][winningOutput] || 0) * 100)}%`; context.font = '500 16px "IBM Plex Mono", monospace'; const labelWidth = context.measureText(label).width; context.strokeStyle = '#ff4d5e'; context.lineWidth = 2; context.shadowBlur = 5; context.shadowColor = '#ff4d5e'; roundRect(winner.x - 16, winner.y - 16, 34 + labelWidth, 32, 5); context.stroke(); context.shadowBlur = 0; }
    const drawNeurons = (items, layer) => items.forEach((point, index) => { const value = state.activations[layer][index] || 0; const pulse = hasSignal ? .5 + .5 * Math.sin(animationTime / 180 + index * .8 + layer) : 0; const glow = Math.min(1, value * 1.5 + value * pulse * .65); const isWinner = layer === 3 && index === winningOutput; const radius = layer === 3 ? 12 : items.length > 20 ? 8 : 10; context.shadowBlur = isWinner ? 26 : hasSignal ? Math.min(18, glow * 18) : 0; context.shadowColor = isWinner ? '#f2f7e2' : '#f2f7e2'; context.fillStyle = isWinner ? '#d9e2e8' : `rgba(242,247,226,${.28 + glow * .72})`; context.beginPath(); context.arc(point.x, point.y, radius, 0, Math.PI * 2); context.fill(); context.shadowBlur = 0; context.strokeStyle = isWinner ? '#d9e2e8' : '#4d5d66'; context.lineWidth = isWinner ? 2.2 : 1.4; context.stroke(); if (layer === 3) drawText(`${index}: ${Math.round(value * 100)}%`, point.x + 18, point.y + 5, 16); });
    drawNeurons(first, 1); drawNeurons(second, 2); drawNeurons(output, 3); drawText('INPUT MATRIX', input.x, 90, 17); drawText('HIDDEN 1', stages.hidden1.x - 18, 30, 18, 'center'); drawText('HIDDEN 2', stages.hidden2.x - 18, 30, 18, 'center'); drawText('OUTPUT', stages.output.x - 20, 30, 18, 'center'); drawText(hasSignal ? 'SIGNAL ACTIVE' : 'WAITING FOR INPUT', 32, 405, 15); drawText('28 x 28 centered', input.x, 420, 17); drawText(`${DigitModel.sizes[1]} ReLU neurons`, stages.hidden1.x - 18, 515, 17, 'center'); drawText(`${DigitModel.sizes[2]} ReLU neurons`, stages.hidden2.x - 18, 515, 17, 'center'); drawText(`${DigitModel.sizes[3]} class probabilities`, 900, 515, 17, 'right');
  }
  function update(result) { state = { ...result, activations: DigitModel.sizes.map((size, index) => result.activations[index]?.slice(0, size) || Array(size).fill(index === 3 ? .1 : 0)) }; hasSignal = state.activations[0].some(value => value > 0); draw(animationTime); }
  function animate(time) { draw(time); window.requestAnimationFrame(animate); }
  window.addEventListener('resize', () => draw(animationTime)); window.requestAnimationFrame(animate); return { update };
})();