const NetworkViz = (() => {
  const canvas = document.getElementById('network-canvas'); const context = canvas.getContext('2d');
  const stages = { input: { x: 32, y: 128, size: 224 }, hidden1: { x: 370 }, hidden2: { x: 590 }, output: { x: 780 } };
  let state = { activations: [Array(784).fill(0), Array(16).fill(0), Array(16).fill(0), Array(10).fill(.1)], weights: [] }; let animationTime = 0; let hasSignal = false;
  function neurons(x, count, top = 70, gap = 28) { return Array.from({ length: count }, (_, index) => ({ x, y: top + index * gap })); }
  function drawArrow(x1, x2, label) { context.strokeStyle = '#4b7779'; context.lineWidth = 1.5; context.setLineDash([5, 5]); context.beginPath(); context.moveTo(x1, 290); context.lineTo(x2, 290); context.stroke(); context.setLineDash([]); context.fillStyle = '#d1eeea'; context.font = '700 16px "DM Mono", monospace'; context.textAlign = 'center'; context.fillText(label, (x1 + x2) / 2, 272); context.beginPath(); context.moveTo(x2, 290); context.lineTo(x2 - 9, 283); context.lineTo(x2 - 9, 297); context.closePath(); context.fill(); }
  function drawSignal(x1, x2, offset) { if (!hasSignal) return; const progress = ((animationTime / 1500 + offset) % 1); const x = x1 + (x2 - x1) * progress; context.shadowBlur = 12; context.shadowColor = '#73e6dc'; context.fillStyle = '#73e6dc'; context.beginPath(); context.arc(x, 290, 3, 0, Math.PI * 2); context.fill(); context.shadowBlur = 0; }
  function draw(time = 0) {
    animationTime = time; context.clearRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#080e10'; context.fillRect(0, 0, canvas.width, canvas.height);
    const input = stages.input; const cell = input.size / 28; context.strokeStyle = '#506158'; context.lineWidth = 1; context.strokeRect(input.x, input.y, input.size, input.size);
    for (let y = 0; y < 28; y += 1) for (let x = 0; x < 28; x += 1) { const value = state.activations[0][y * 28 + x] || 0; context.fillStyle = `rgb(${Math.round(22 + value * 225)},${Math.round(35 + value * 212)},${Math.round(29 + value * 197)})`; context.fillRect(input.x + x * cell, input.y + y * cell, cell + .3, cell + .3); }
    const first = neurons(stages.hidden1.x, 16); const second = neurons(stages.hidden2.x, 16); const output = neurons(stages.output.x, 10, 112, 38);
    const connect = (from, to, layer) => from.forEach((a, ai) => to.forEach((b, bi) => { const weight = state.weights[layer]?.[bi]?.[ai] || 0; const sourceValue = state.activations[layer]?.[ai] || 0; const targetValue = state.activations[layer + 1]?.[bi] || 0; if (!weight || (!hasSignal && layer > 0)) return; const pulse = .5 + .5 * Math.sin(animationTime / 220 + ai * .7 + bi * .3); const active = Math.min(1, sourceValue * targetValue * 5); const alpha = Math.min(.72, .04 + Math.abs(weight) * .45 + active * (.18 + pulse * .2)); context.strokeStyle = weight > 0 ? `rgba(74,157,255,${alpha})` : `rgba(255,113,128,${alpha})`; context.lineWidth = Math.min(2.5, .25 + Math.abs(weight) * .9 + active * pulse * 1.2); context.beginPath(); context.moveTo(a.x, a.y); context.lineTo(b.x, b.y); context.stroke(); }));
    connect(first, second, 1); connect(second, output, 2); drawArrow(input.x + input.size, stages.hidden1.x - 18, '784 PIXELS'); drawArrow(stages.hidden1.x + 18, stages.hidden2.x - 18, 'RELU'); drawArrow(stages.hidden2.x + 18, stages.output.x - 18, 'SOFTMAX'); drawSignal(input.x + input.size, stages.hidden1.x - 18, 0); drawSignal(stages.hidden1.x + 18, stages.hidden2.x - 18, .33); drawSignal(stages.hidden2.x + 18, stages.output.x - 18, .66);
    const winningOutput = state.activations[3].indexOf(Math.max(...state.activations[3]));
    const drawNeurons = (items, layer) => items.forEach((point, index) => { const value = state.activations[layer][index] || 0; const pulse = hasSignal ? .5 + .5 * Math.sin(animationTime / 180 + index * .8 + layer) : 0; const glow = Math.min(1, value * 1.2 + value * pulse * .45); const isWinner = layer === 3 && index === winningOutput; context.shadowBlur = hasSignal ? glow * 18 : 0; context.shadowColor = isWinner ? '#d9fb69' : '#73e6dc'; context.fillStyle = isWinner ? '#d9fb69' : `rgba(242,247,226,${.12 + glow * .88})`; context.beginPath(); context.arc(point.x, point.y, (layer === 3 ? 11 : 9) + glow * 2, 0, Math.PI * 2); context.fill(); context.shadowBlur = 0; context.strokeStyle = isWinner ? '#d9fb69' : '#506158'; context.stroke(); if (layer === 3) { context.fillStyle = isWinner ? '#17231d' : '#d9fb69'; context.font = '700 16px "DM Mono", monospace'; context.textAlign = 'left'; context.fillText(`${index}: ${Math.round(value * 100)}%`, point.x + 18, point.y + 5); } });
    drawNeurons(first, 1); drawNeurons(second, 2); drawNeurons(output, 3); context.fillStyle = '#e2f8f3'; context.font = '700 17px "DM Mono", monospace'; context.textAlign = 'left'; context.fillText('INPUT MATRIX', input.x, 105); context.fillText('HIDDEN 1', stages.hidden1.x - 28, 32); context.fillText('HIDDEN 2', stages.hidden2.x - 28, 32); context.fillText('OUTPUT', stages.output.x - 18, 75); context.fillStyle = hasSignal ? '#73e6dc' : '#a2c0ba'; context.font = '700 14px "DM Mono", monospace'; context.fillText(hasSignal ? 'SIGNAL ACTIVE' : 'WAITING FOR INPUT', 32, 405); context.fillStyle = '#a2c0ba'; context.font = '600 14px "DM Mono", monospace'; context.fillText('28 x 28 centered', input.x, 420); context.fillText('16 ReLU neurons', stages.hidden1.x - 42, 515); context.fillText('16 ReLU neurons', stages.hidden2.x - 42, 515); context.fillText('10 class probabilities', stages.output.x - 42, 515);
  }
  function update(result) { state = result; hasSignal = state.activations[0].some(value => value > 0); draw(animationTime); }
  function animate(time) { draw(time); window.requestAnimationFrame(animate); }
  window.addEventListener('resize', () => draw(animationTime)); window.requestAnimationFrame(animate); return { update };
})();