const NetworkViz = (() => {
  const canvas = document.getElementById('network-canvas'); const context = canvas.getContext('2d');
  const stages = { input: { x: 32, y: 128, size: 224 }, hidden1: { x: 370 }, hidden2: { x: 590 }, output: { x: 810 } };
  let state = { activations: [Array(784).fill(0), Array(16).fill(0), Array(16).fill(0), Array(10).fill(.1)], weights: [] };
  function neurons(x, count, top = 70, gap = 28) { return Array.from({ length: count }, (_, index) => ({ x, y: top + index * gap })); }
  function drawArrow(x1, x2, label) { context.strokeStyle = '#829188'; context.lineWidth = 1; context.setLineDash([5, 5]); context.beginPath(); context.moveTo(x1, 290); context.lineTo(x2, 290); context.stroke(); context.setLineDash([]); context.fillStyle = '#aab8aa'; context.font = '10px DM Mono'; context.textAlign = 'center'; context.fillText(label, (x1 + x2) / 2, 278); context.beginPath(); context.moveTo(x2, 290); context.lineTo(x2 - 7, 285); context.lineTo(x2 - 7, 295); context.closePath(); context.fill(); }
  function draw() {
    context.clearRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#17231d'; context.fillRect(0, 0, canvas.width, canvas.height);
    const input = stages.input; const cell = input.size / 28; context.strokeStyle = '#506158'; context.lineWidth = 1; context.strokeRect(input.x, input.y, input.size, input.size);
    for (let y = 0; y < 28; y += 1) for (let x = 0; x < 28; x += 1) { const value = state.activations[0][y * 28 + x] || 0; context.fillStyle = `rgb(${Math.round(22 + value * 225)},${Math.round(35 + value * 212)},${Math.round(29 + value * 197)})`; context.fillRect(input.x + x * cell, input.y + y * cell, cell + .3, cell + .3); }
    const first = neurons(stages.hidden1.x, 16); const second = neurons(stages.hidden2.x, 16); const output = neurons(stages.output.x, 10, 112, 38);
    const connect = (from, to, layer) => from.forEach((a, ai) => to.forEach((b, bi) => { const weight = state.weights[layer]?.[bi]?.[ai] || 0; if (!weight) return; context.strokeStyle = weight > 0 ? `rgba(40,121,255,${Math.min(.55, .08 + Math.abs(weight) * .7)})` : `rgba(255,98,98,${Math.min(.55, .08 + Math.abs(weight) * .7)})`; context.lineWidth = Math.min(2, .3 + Math.abs(weight)); context.beginPath(); context.moveTo(a.x, a.y); context.lineTo(b.x, b.y); context.stroke(); }));
    connect(first, second, 1); connect(second, output, 2); drawArrow(input.x + input.size, stages.hidden1.x - 18, '784 PIXELS'); drawArrow(stages.hidden1.x + 18, stages.hidden2.x - 18, 'RELU'); drawArrow(stages.hidden2.x + 18, stages.output.x - 18, 'SOFTMAX');
    const winningOutput = state.activations[3].indexOf(Math.max(...state.activations[3]));
    const drawNeurons = (items, layer) => items.forEach((point, index) => { const value = state.activations[layer][index] || 0; const glow = Math.min(1, value * 1.2); context.fillStyle = layer === 3 && index === winningOutput ? '#d9fb69' : `rgba(242,247,226,${.12 + glow * .88})`; context.beginPath(); context.arc(point.x, point.y, layer === 3 ? 10 : 9, 0, Math.PI * 2); context.fill(); context.strokeStyle = '#506158'; context.stroke(); if (layer === 3) { context.fillStyle = index === winningOutput ? '#17231d' : '#d9fb69'; context.font = '12px DM Mono'; context.textAlign = 'left'; context.fillText(`${index}  ${Math.round(value * 100)}%`, point.x + 17, point.y + 4); } });
    drawNeurons(first, 1); drawNeurons(second, 2); drawNeurons(output, 3); context.fillStyle = '#91a197'; context.font = '11px DM Mono'; context.textAlign = 'left'; context.fillText('INPUT MATRIX', input.x, 110); context.fillText('HIDDEN 1', stages.hidden1.x - 28, 32); context.fillText('HIDDEN 2', stages.hidden2.x - 28, 32); context.fillText('OUTPUT', stages.output.x - 18, 75); context.fillStyle = '#758078'; context.font = '10px DM Mono'; context.fillText('28 x 28 centered', input.x, 370); context.fillText('16 ReLU neurons', stages.hidden1.x - 42, 515); context.fillText('16 ReLU neurons', stages.hidden2.x - 42, 515); context.fillText('10 class probabilities', stages.output.x - 42, 515);
  }
  function update(result) { state = result; draw(); }
  window.addEventListener('resize', draw); draw(); return { update };
})();